import express from 'express';
import authRoutes from './authRoutes.js';
import productRoutes from './productRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import attributeRoutes from './attributeRoutes.js';
import branchRoutes from './branchRoutes.js';
import recipeRoutes from './recipeRoutes.js';
import salesRoutes from './salesRoutes.js';
import salesReturnRoutes from './salesReturnRoutes.js';
import purchaseReturnRoutes from './purchaseReturnRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import importExportRoutes from './importExportRoutes.js';
import customerRoutes from './customerRoutes.js';
import supplierRoutes from './supplierRoutes.js';
import purchaseRoutes from './purchaseRoutes.js';
import expenseRoutes from './expenseRoutes.js';
import payrollRoutes from './payrollRoutes.js';
import userRoutes from './userRoutes.js';
import roleRoutes from './roleRoutes.js';
import reportRoutes from './reportRoutes.js';
import paymentAccountRoutes from './paymentAccountRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import taxRoutes from './taxRoutes.js';
import agentRoutes from './agentRoutes.js';
import discountRoutes from './discountRoutes.js';
import deliveryNoteRoutes from './deliveryNoteRoutes.js';
import printRoutes from './printRoutes.js';
import printerRoutes from './printerRoutes.js';

const router = express.Router();

// Mount route modules
router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/attributes', attributeRoutes);
router.use('/branches', branchRoutes);
router.use('/recipes', recipeRoutes);
router.use('/sales', salesRoutes);
router.use('/sales-returns', salesReturnRoutes);
router.use('/purchase-returns', purchaseReturnRoutes);
router.use('/payments', paymentRoutes);
router.use('/customers', customerRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/expenses', expenseRoutes);
router.use('/payroll', payrollRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/reports', reportRoutes);
router.use('/payment-accounts', paymentAccountRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/tax-rates', taxRoutes);
router.use('/agents', agentRoutes);
router.use('/discounts', discountRoutes);
router.use('/delivery-notes', deliveryNoteRoutes);
router.use('/print', printRoutes);
router.use('/receipt-printers', printerRoutes);
router.use('/', importExportRoutes);

export default router;

